server:
  port: 8081

spring:
  application:
    name: alibouSecurity
  datasource:
    url: jdbc:postgresql://localhost:5433/alibouDB
    username: usr
    password: pwd
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 4c9f8e2c8a0c1e7f3d8a1a5c8b2e6d9a8c5e7b4f3a2d6e9f3b1a7e8c4a9e0c1a
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
      bearer-prefix: "Bearer "

logging:
  level:
    root: info
    sql: trace